// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1620900889);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1620900649);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1620900769);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1620900679);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1620901009);
user_pref("browser.cache.disk.amount_written", 853);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("calendar.list.sortOrder", "9ddfe763-971a-4a63-ae22-ea247e716673");
user_pref("calendar.registry.9ddfe763-971a-4a63-ae22-ea247e716673.calendar-main-in-composite", true);
user_pref("calendar.registry.9ddfe763-971a-4a63-ae22-ea247e716673.disabled", true);
user_pref("calendar.registry.9ddfe763-971a-4a63-ae22-ea247e716673.name", "Home");
user_pref("calendar.registry.9ddfe763-971a-4a63-ae22-ea247e716673.type", "storage");
user_pref("calendar.registry.9ddfe763-971a-4a63-ae22-ea247e716673.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Beirut");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1620900631977");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1620900889);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.8.1");
user_pref("extensions.lastPlatformVersion", "78.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"9320a242-5b14-4083-802e-b82c08bb4442\",\"default-theme@mozilla.org\":\"6932b6c5-076f-4c4a-842e-fa297b169315\",\"google@search.mozilla.org\":\"a838f9d0-f625-426a-8e07-2d3b0d0e1025\",\"amazondotcom@search.mozilla.org\":\"ace4cfdf-d58e-4613-a5f1-7141600ca719\",\"bing@search.mozilla.org\":\"b7e90d76-3ebe-4d7b-b8cf-ff1404691874\",\"ddg@search.mozilla.org\":\"d10c9314-9839-4430-b795-024d254aab12\",\"wikipedia@search.mozilla.org\":\"c231ad65-b8d9-41ae-b3e6-1acaeff62513\"}");
user_pref("idle.lastDailyNotification", 1620901262);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "b70e27a7-6488-4505-b1bb-6805bba3937");
user_pref("mailnews.filters.migration78", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "78.8.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("places.database.lastMaintenance", 1620901262);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("security.sandbox.plugin.tempDirSuffix", "df15485b-09bd-4027-af63-0dbf8e025a46");
user_pref("services.blocklist.addons.checked", 1620900770);
user_pref("services.settings.clock_skew_seconds", -1);
user_pref("services.settings.last_etag", "\"1620892700288\"");
user_pref("services.settings.last_update_seconds", 1620900770);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1620900770);
user_pref("services.settings.main.hijack-blocklists.last_check", 1620900770);
user_pref("services.settings.main.language-dictionaries.last_check", 1620900770);
user_pref("services.settings.main.search-config.last_check", 1620900770);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1620900770);
user_pref("services.settings.main.sites-classification.last_check", 1620900770);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1620900770);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1620901262);
user_pref("toolkit.telemetry.cachedClientID", "e80fd73b-4f5f-4bd8-878a-2d7fb9a0a42a");
user_pref("toolkit.telemetry.previousBuildID", "20210304234616");
user_pref("ui.systemUsesDarkTheme", 1);
